### ISSUE TITLE
Foundry throw an error with the smallTime module

### ISSUE THREAD

**Issue by IvanZadorozhniy** [unsoluble/smalltime#204]
When I added Smalltime module i got an error in the console. You can see it in the video below. 

https://github.com/unsoluble/smalltime/assets/91192276/3d49f9bb-4d35-47e4-8f7b-6ad250ffd77b

The error text:

Error: Error thrown in hooked function '' for hook 'canvasInit'. Cannot read properties of undefined (reading 'dispatchEvent')
    at Hooks.onError (foundry.js:630:24)
    at #call (foundry.js:612:36)
    at Hooks.callAll (foundry.js:565:17)
    at #draw (foundry.js:24687:11)
    at async Canvas.draw (foundry.js:24615:5)
    at async Scene.view (foundry.js:21117:7)
    at async Game.initializeCanvas (foundry.js:9166:20)
    at async Game.setupGame (foundry.js:8993:5)
    at async Game._initializeGameView (foundry.js:10306:5)
    at async Game.initialize (foundry.js:8896:5)

If it is an feature, not the bug, then ok. Just close the issue)

**Comment by unsoluble** [comment]
Thanks for flagging this! Fixed and cleaned up some deprecation warnings in 1.20.0
